

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mts
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    show-sql: true  
    
    
